services:
  andrej_zafirovski_web:
    build: .
    container_name: andrej_zafirovski_web
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.andrej_zafirovski_web.rule=Host(`andrejzafirovski.com`)"
      - "traefik.http.routers.andrej_zafirovski_web.tls=true"
      - "traefik.http.routers.andrej_zafirovski_web.tls.certresolver=letsencrypt"
      - "traefik.http.services.andrej_zafirovski_web.loadbalancer.server.port=3000"
    networks:
      - traefik
networks:
  traefik:
    external: true
